In [1]:
import numpy as np

print(1)
print(2)
print(1)
print(2)
print(1)
print(2)

1
2
1
2
1
2


In [278]:
import sys
sys.version

'3.9.12 (main, Apr  5 2022, 06:56:58) \n[GCC 7.5.0]'

In [280]:
!pip install TA-Lib

Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels


In [273]:
!pip install --user TA-Lib

Looking in links: /usr/share/pip-wheels


In [276]:
!{sys.executable} -m pip install --user TA-Lib


Looking in links: /usr/share/pip-wheels


In [236]:
print(talib.__version__)

NameError: name 'talib' is not defined

In [ ]:
import talib as ta

In [240]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler,MinMaxScaler

In [242]:
df=pd.read_csv('stock.csv')[:800]
# df[['A', 'B', 'C']] = scaler.fit_transform(df[['A', 'B', 'C']])

In [244]:
print(df)

           Date     Open     High      Low    Close  Adj Close  Volume
0    2020-01-09  45900.0  47850.0  45900.0  47400.0    47400.0    6698
1    2020-01-10  53700.0  54000.0  49050.0  49500.0    49500.0   97319
2    2020-01-13  49500.0  50700.0  47100.0  49500.0    49500.0   25237
3    2020-01-14  49800.0  49800.0  48600.0  49800.0    49800.0    9862
4    2020-01-15  50700.0  50700.0  49350.0  49950.0    49950.0   10599
..          ...      ...      ...      ...      ...        ...     ...
795  2023-03-30  11790.0  12000.0  11610.0  11820.0    11820.0    7624
796  2023-03-31  11820.0  11820.0  11580.0  11700.0    11700.0    5311
797  2023-04-03  11700.0  11700.0  11550.0  11700.0    11700.0    5263
798  2023-04-04  11700.0  11880.0  11550.0  11760.0    11760.0    6703
799  2023-04-05  11850.0  12210.0  11790.0  12180.0    12180.0   17027

[800 rows x 7 columns]


In [246]:
df['Date']=pd.to_datetime(df['Date'])
print(df)

          Date     Open     High      Low    Close  Adj Close  Volume
0   2020-01-09  45900.0  47850.0  45900.0  47400.0    47400.0    6698
1   2020-01-10  53700.0  54000.0  49050.0  49500.0    49500.0   97319
2   2020-01-13  49500.0  50700.0  47100.0  49500.0    49500.0   25237
3   2020-01-14  49800.0  49800.0  48600.0  49800.0    49800.0    9862
4   2020-01-15  50700.0  50700.0  49350.0  49950.0    49950.0   10599
..         ...      ...      ...      ...      ...        ...     ...
795 2023-03-30  11790.0  12000.0  11610.0  11820.0    11820.0    7624
796 2023-03-31  11820.0  11820.0  11580.0  11700.0    11700.0    5311
797 2023-04-03  11700.0  11700.0  11550.0  11700.0    11700.0    5263
798 2023-04-04  11700.0  11880.0  11550.0  11760.0    11760.0    6703
799 2023-04-05  11850.0  12210.0  11790.0  12180.0    12180.0   17027

[800 rows x 7 columns]


In [248]:
df['Date']=pd.to_datetime(df['Date'])
print(df)

          Date     Open     High      Low    Close  Adj Close  Volume
0   2020-01-09  45900.0  47850.0  45900.0  47400.0    47400.0    6698
1   2020-01-10  53700.0  54000.0  49050.0  49500.0    49500.0   97319
2   2020-01-13  49500.0  50700.0  47100.0  49500.0    49500.0   25237
3   2020-01-14  49800.0  49800.0  48600.0  49800.0    49800.0    9862
4   2020-01-15  50700.0  50700.0  49350.0  49950.0    49950.0   10599
..         ...      ...      ...      ...      ...        ...     ...
795 2023-03-30  11790.0  12000.0  11610.0  11820.0    11820.0    7624
796 2023-03-31  11820.0  11820.0  11580.0  11700.0    11700.0    5311
797 2023-04-03  11700.0  11700.0  11550.0  11700.0    11700.0    5263
798 2023-04-04  11700.0  11880.0  11550.0  11760.0    11760.0    6703
799 2023-04-05  11850.0  12210.0  11790.0  12180.0    12180.0   17027

[800 rows x 7 columns]


In [250]:
df.index=df['Date']
print(df)
df=df.drop(["Date"],axis=1)
print(df)

                 Date     Open     High      Low    Close  Adj Close  Volume
Date                                                                        
2020-01-09 2020-01-09  45900.0  47850.0  45900.0  47400.0    47400.0    6698
2020-01-10 2020-01-10  53700.0  54000.0  49050.0  49500.0    49500.0   97319
2020-01-13 2020-01-13  49500.0  50700.0  47100.0  49500.0    49500.0   25237
2020-01-14 2020-01-14  49800.0  49800.0  48600.0  49800.0    49800.0    9862
2020-01-15 2020-01-15  50700.0  50700.0  49350.0  49950.0    49950.0   10599
...               ...      ...      ...      ...      ...        ...     ...
2023-03-30 2023-03-30  11790.0  12000.0  11610.0  11820.0    11820.0    7624
2023-03-31 2023-03-31  11820.0  11820.0  11580.0  11700.0    11700.0    5311
2023-04-03 2023-04-03  11700.0  11700.0  11550.0  11700.0    11700.0    5263
2023-04-04 2023-04-04  11700.0  11880.0  11550.0  11760.0    11760.0    6703
2023-04-05 2023-04-05  11850.0  12210.0  11790.0  12180.0    12180.0   17027

In [311]:
df['MA']=ta.SMA(df.Close,90)
df=df.fillna(0)
df['RSI']=ta.RSI(df.Close,14)
df["STOCH_K"],df["STOCH_D"]=ta.STOCH(df["High"],df["Low"],df["Close"],fastk_period=14,slowk_period=3,slowk_matype=0)

df["MACD"],df["MACDSignal"],df["MACDHist"]=ta.MACD(df.Close,fastperiod=12,slowperiod=26,signalperiod=9)
df["WILLR"]=ta.WILLR(df["High"],df["Low"],df["Close"],timeperiod=14)

MA=df["MA"].rolling('5d').apply(lambda x: np.sign(x[-1]-x[0]),raw=False)
df["Trend"]=df["MA"].rolling('5d').apply(lambda x: np.sign(x[-1]-x[0]),raw=False)
def f(row):
    if row['Close'] > row['MA'] and row['Trend'] == 1:
        val = 1
    elif row['Close'] < row['MA'] and row['Trend'] == -1:
        val = 0
    else:
        val = 0
    return val
df['Trend'] = df.apply(f, axis=1, raw=False)



In [312]:
# MA,RSI,WILLR都用到了当天的数据，在计算trend时需要，但是在模型输入中要平移一天
df['MA'] = df['MA'].shift(1)
df['MACD'] = df['MACD'].shift(1)
df['WILLR'] = df['WILLR'].shift(1)
df['RSI']= df['RSI'].shift(1)


In [315]:
print(df['MA'][87:100])
print(df['STOCH_K'][0:20])
print(df['STOCH_D'][0:20])
print(df['High'])
print(df['Low'])
print(df['MACD'][30:90])

Date
2020-05-19        0.000000
2020-05-20        0.000000
2020-05-21        0.000000
2020-05-22    43360.666667
2020-05-25    43339.000000
2020-05-26    43289.000000
2020-05-27    43237.333333
2020-05-28    43182.333333
2020-05-29    43124.000000
2020-06-01    43064.000000
2020-06-02    42995.666667
2020-06-03    42949.000000
2020-06-04    42905.666667
Name: MA, dtype: float64
Date
2020-01-09          NaN
2020-01-10          NaN
2020-01-13          NaN
2020-01-14          NaN
2020-01-15          NaN
2020-01-16    59.761905
2020-01-17    60.687831
2020-01-20    45.319865
2020-01-21    34.550635
2020-01-22     8.624709
2020-01-23    19.230769
2020-01-28    20.000000
2020-01-29    35.686275
2020-01-30    20.606909
2020-01-31    24.965884
2020-02-03    29.279609
2020-02-04    59.791073
2020-02-05    65.142244
2020-02-06    67.364466
2020-02-07    63.837129
Name: STOCH_K, dtype: float64
Date
2020-01-09          NaN
2020-01-10          NaN
2020-01-13          NaN
2020-01-14          NaN
202

In [317]:
# MA=np.where(MA==1,1,0)
# print(MA[80:100])

In [319]:
# MA_Clos=np.where(df["Close"]>df['MA'],1,0)
# print("MA_Clos:")
# print(len(MA_Clos))
# print("MA")
# print(len(MA))
# Tr=MA.mul(MA_Clos)
# print("Tr:")
# print(len(Tr))


#df['WILLR']=ta.WILLR(df['MA','RSI'])

In [321]:
Close=df["Close"]
# df["Tri"]=((Close-Close.rolling('3 d').min())/(Close.rolling('3 d').max()-Close.rolling('3 d').min()))* 0.5  + 0.5*df['Trend']
# df["DownTri"]=(Close-Close.rolling('3d').min())/(Close.rolling('3d').max()-Close.rolling('3d').min())* .5

In [323]:
# 归一化
print(df)
scaler = MinMaxScaler()
df[["MA", "MACD", "RSI", "WILLR", "STOCH_K", "STOCH_D"]] = scaler.fit_transform(df[["MA", "MACD", "RSI", "WILLR", "STOCH_K", "STOCH_D"]])
print(df)

# print(df["Tri"])

               Open     High      Low    Close  Adj Close  Volume  \
Date                                                                
2020-01-09  45900.0  47850.0  45900.0  47400.0    47400.0    6698   
2020-01-10  53700.0  54000.0  49050.0  49500.0    49500.0   97319   
2020-01-13  49500.0  50700.0  47100.0  49500.0    49500.0   25237   
2020-01-14  49800.0  49800.0  48600.0  49800.0    49800.0    9862   
2020-01-15  50700.0  50700.0  49350.0  49950.0    49950.0   10599   
...             ...      ...      ...      ...        ...     ...   
2023-03-30  11790.0  12000.0  11610.0  11820.0    11820.0    7624   
2023-03-31  11820.0  11820.0  11580.0  11700.0    11700.0    5311   
2023-04-03  11700.0  11700.0  11550.0  11700.0    11700.0    5263   
2023-04-04  11700.0  11880.0  11550.0  11760.0    11760.0    6703   
2023-04-05  11850.0  12210.0  11790.0  12180.0    12180.0   17027   

                      MA        RSI    STOCH_K    STOCH_D        MACD  \
Date                         

In [287]:
Close=df["Close"]
print(Close[14])
# df["UpTrend"] = ((Close - Close.rolling('3 D').min())/(Close.rolling('3 D').max() - Close.rolling('3 D').min()) * .5) + .5
# df["DownTrend"] = (Close - Close.rolling('3 D').min())/(Close.rolling('3 D').max() - Close.rolling('3 D').min()) * .5

df["UpTrend"] = (Close.shift(-3) - Close.shift(-3).rolling('3D').min()) / (Close.shift(-3).rolling('3D').max() - Close.shift(-3).rolling('3D').min()) * 0.5+0.5
df["DownTrend"] = (Close.shift(-3) - Close.shift(-3).rolling('3D').min()) / (Close.shift(-3).rolling('3D').max() - Close.shift(-3).rolling('3D').min()) * 0.5

def g(row):
    if row['Trend'] == 1:
        val = row['UpTrend']
    elif row['Trend'] == 0:
        val = row['DownTrend']
    else:
        val = 0
    return val
df['Trade_Signal'] = df.apply(g, axis=1, raw=False)

45000.0


In [288]:
print(df['Trade_Signal'])

Date
2020-01-09    NaN
2020-01-10    0.5
2020-01-13    NaN
2020-01-14    0.5
2020-01-15    0.0
             ... 
2023-03-30    0.5
2023-03-31    0.5
2023-04-03    NaN
2023-04-04    NaN
2023-04-05    NaN
Name: Trade_Signal, Length: 800, dtype: float64


In [268]:
print(df['Trade_Signal'][50:100])
print(df['Tri'][50:100])

Date
2020-03-23         NaN
2020-03-24    0.500000
2020-03-25    0.500000
2020-03-26    0.500000
2020-03-27    0.363636
2020-03-30         NaN
2020-03-31    0.500000
2020-04-01    0.500000
2020-04-02    0.500000
2020-04-03    0.500000
2020-04-06         NaN
2020-04-07    0.000000
2020-04-08    0.500000
2020-04-09    0.500000
2020-04-10    0.500000
2020-04-13         NaN
2020-04-14    0.500000
2020-04-16    0.500000
2020-04-17    0.500000
2020-04-20         NaN
2020-04-21    0.000000
2020-04-22    0.000000
2020-04-23    0.000000
2020-04-24    0.000000
2020-04-27         NaN
2020-04-28    0.500000
2020-04-29    0.083333
2020-05-04         NaN
2020-05-06    0.500000
2020-05-07    0.500000
2020-05-08    0.500000
2020-05-11         NaN
2020-05-12    0.000000
2020-05-13    0.166667
2020-05-14    0.000000
2020-05-15    0.000000
2020-05-18         NaN
2020-05-19    0.500000
2020-05-20    0.500000
2020-05-21    1.000000
2020-05-22    0.500000
2020-05-25         NaN
2020-05-26    0.000000
2020-0

KeyError: 'Tri'

In [43]:
features=pd.concat([df['MA'],df['RSI'],df["STOCH_K"],df["STOCH_D"],df["MACD"],df["WILLR"]],axis=1)
print(features)

                  MA       RSI   STOCH_K   STOCH_D      MACD     WILLR
Date                                                                  
2020-01-09  0.000000       NaN       NaN       NaN       NaN       NaN
2020-01-10  0.000000       NaN       NaN       NaN       NaN       NaN
2020-01-13  0.000000       NaN       NaN       NaN       NaN       NaN
2020-01-14  0.000000       NaN       NaN       NaN       NaN       NaN
2020-01-15  0.000000       NaN       NaN       NaN       NaN       NaN
...              ...       ...       ...       ...       ...       ...
2023-12-01  0.007591  0.979307  0.994191  0.945714  0.324367  0.977221
2023-12-04  0.006878  0.979578  0.998064  0.998712  0.328627  0.982906
2023-12-05  0.006215  0.961667  0.998059  0.998064  0.331335  0.971510
2023-12-06  0.006749  0.962568  0.999987  1.000000  0.333112  0.982882
2023-12-07  0.007336  0.969251  0.983805  0.995238  0.335245  0.935404

[966 rows x 6 columns]


In [163]:
target=df['Tri']
print(target)

KeyError: 'Tri'

In [47]:
target=target.fillna(0.5)
features=features.fillna(0.5)
print(target[50:100])
print(features[50:100])

Date
2020-03-23    0.500000
2020-03-24    0.500000
2020-03-25    0.500000
2020-03-26    0.500000
2020-03-27    0.363636
2020-03-30    0.500000
2020-03-31    0.500000
2020-04-01    0.500000
2020-04-02    0.500000
2020-04-03    0.500000
2020-04-06    0.500000
2020-04-07    0.000000
2020-04-08    0.500000
2020-04-09    0.500000
2020-04-10    0.500000
2020-04-13    0.500000
2020-04-14    0.500000
2020-04-16    0.500000
2020-04-17    0.500000
2020-04-20    0.500000
2020-04-21    0.000000
2020-04-22    0.000000
2020-04-23    0.000000
2020-04-24    0.000000
2020-04-27    0.500000
2020-04-28    0.500000
2020-04-29    0.083333
2020-05-04    0.500000
2020-05-06    0.500000
2020-05-07    0.500000
2020-05-08    0.500000
2020-05-11    0.500000
2020-05-12    0.000000
2020-05-13    0.166667
2020-05-14    0.000000
2020-05-15    0.000000
2020-05-18    0.500000
2020-05-19    0.500000
2020-05-20    0.500000
2020-05-21    1.000000
2020-05-22    0.500000
2020-05-25    0.500000
2020-05-26    0.000000
2020-0

In [49]:
df2 = pd.concat([features, target], axis=1)
print(df2[50:100])

                  MA       RSI   STOCH_K   STOCH_D      MACD     WILLR  \
Date                                                                     
2020-03-23  0.000000  0.069753  0.061169  0.068869  0.005985  0.061327   
2020-03-24  0.000000  0.094683  0.081264  0.070788  0.000000  0.086902   
2020-03-25  0.000000  0.169169  0.110233  0.083807  0.005931  0.177267   
2020-03-26  0.000000  0.229887  0.179346  0.123274  0.020301  0.264205   
2020-03-27  0.000000  0.221672  0.239501  0.176118  0.032824  0.263482   
2020-03-30  0.000000  0.269223  0.291443  0.236635  0.050630  0.329738   
2020-03-31  0.000000  0.326112  0.349482  0.293453  0.073794  0.434572   
2020-04-01  0.000000  0.326112  0.473334  0.371543  0.094376  0.627040   
2020-04-02  0.000000  0.372621  0.610349  0.478043  0.118031  0.731935   
2020-04-03  0.000000  0.446173  0.782646  0.622701  0.147972  0.940334   
2020-04-06  0.000000  0.479218  0.898320  0.764628  0.177757  0.966592   
2020-04-07  0.000000  0.474202  0.9509

In [219]:
n=6
d=6

# ones_matrix=pd.DataFrame(data=1, index=range(n),columns=range(1))
initial_weights=np.random.uniform(low=0,high=1,size=(n,d+1))

train=df2.iloc[:1000,:]
test=df2.iloc[1000:,:]
target_column=['Tri']
# predictors=list(set(list(df2.columns))-set(target_column))
y=train['Tri']
X=train.iloc[:,0:6]
ONE=np.ones((len(X),1))
X=np.hstack((ONE,X))
# X: n*(d+1)
nparray=np.empty((len(X),n+1))
for i in range(len(X)):
    nparray[i]=np.array(X[i,:])
expanded_inputs=np.empty((len(X),n))
for i in range(len(X)):
    for j in range(n):
        array=np.mat(nparray[i])
        # print(array)
        # print(array.T.dot([initial_weights[j]]).shape)
        expanded_inputs[i,j]=np.dot(array, initial_weights[j])
        #array.dot([initial_weights[j]])
        # expanded_inputs[i,j]=X.iloc[i].dot(initial_weights[j])
#test_expanded_inputs=
print(expanded_inputs.shape)
print(expanded_inputs[80:100])

df2=df2.iloc[:800,:].copy()
print(df2)


NameError: name 'df2' is not defined

In [217]:
df3=df2.copy(deep=True)
print(df3)
df3.rename(columns={'Tri':'cx1','MA':'cx2','MACD':'cx3','RSI':'cx4','STOCH_D':'cx5','STOCH_K':'cx6'},inplace=True)
print(df3)
print(df3.columns)
df4=df3.drop(columns=['WILLR'])
print(df4)
for i in range(len(features)):
    df4['cx1'][i]=1
print(df4)    
# # df3['Date']=df['Date'].copy()
# # df3['cx1']=pd.DataFrame(expanded_inputs[:,0])
target_column = ['Tri'] 
predictors = list(set(list(df4.columns)))
# indices=df['Date']
print(expanded_inputs)
# df3.drop('MA',axis=1)
data_df = pd.DataFrame(expanded_inputs, index=df4.index, columns=predictors)


NameError: name 'df2' is not defined

In [112]:
print(expanded_inputs[80:100])

[[2.38720039 2.60359403 1.8334508  2.1863517  1.77558731 2.28210692]
 [2.41181627 2.65736115 1.87854811 2.19088314 1.78989976 2.31690797]
 [2.38023854 2.66463799 1.88301062 2.146075   1.7716929  2.30883637]
 [2.38670038 2.67203014 1.89295487 2.16680081 1.78254056 2.32604482]
 [2.16720361 2.51042212 1.72991387 1.92051392 1.64276591 2.15998112]
 [1.99078723 2.32937256 1.56650639 1.76584303 1.53346247 2.00185457]
 [1.95124262 2.21211289 1.47430944 1.78706566 1.51249693 1.93342312]
 [2.08613901 2.2658139  1.53171489 1.93972056 1.58456587 1.99657297]
 [2.18483924 2.35689402 1.61150077 2.00797595 1.6298765  2.0569381 ]
 [2.39676418 2.82653845 2.17303261 2.57736012 1.89896891 2.18780861]
 [2.13446454 2.66843097 2.0195649  2.288046   1.73969553 2.00821969]
 [1.96298992 2.5086347  1.87711743 2.14601987 1.64265631 1.87648103]
 [1.75805154 2.27132472 1.66378529 1.98176508 1.51772565 1.6853557 ]
 [1.68566304 2.13158985 1.54413764 1.93870863 1.46080824 1.57020469]
 [1.60990636 2.01130274 1.4384997 

In [116]:
# aa=features['MA'].copy()
# # print(aa)
# # print(aa.shape)
# for i in range(len(aa)):
#     aa[i]=1
# print(aa)
# print(features['MA'])
features['aa']=features['MA'].copy()
for i in range(len(features)):
    features['aa'][i]=1
print(features)
features1=features.drop(columns='aa')
# expanded_inputs=pd.concat([train.iloc[:,0:6],expanded_inputs],axis=1)
# expanded_inputs=pd.concat(features,expanded_inputs)
# ONE=np.ones((len(X),1))

# features1=np.hstack((ONE,features))

# one=[1]*966
# ONE=pd.DataFrame(one)
# print(ONE.shape)
# print(features.shape)
# features1=pd.DataFrame()
# print(features1.shape)
# features1=pd.concat([aa,features],axis=1)
# print(features1.shape)
print(expanded_inputs.shape)
expanded_inputs1=pd.DataFrame(expanded_inputs)
print(expanded_inputs1.shape)
print(expanded_inputs1)
expanded_inputs2=pd.concat([features1,data_df],axis=1)
print(expanded_inputs2.shape)
print(expanded_inputs2)


#data_df


                  MA       RSI   STOCH_K   STOCH_D      MACD     WILLR   aa
Date                                                                       
2020-01-09  0.000000  0.500000  0.500000  0.500000  0.500000  0.500000  1.0
2020-01-10  0.000000  0.500000  0.500000  0.500000  0.500000  0.500000  1.0
2020-01-13  0.000000  0.500000  0.500000  0.500000  0.500000  0.500000  1.0
2020-01-14  0.000000  0.500000  0.500000  0.500000  0.500000  0.500000  1.0
2020-01-15  0.000000  0.500000  0.500000  0.500000  0.500000  0.500000  1.0
...              ...       ...       ...       ...       ...       ...  ...
2023-12-01  0.007591  0.979307  0.994191  0.945714  0.324367  0.977221  1.0
2023-12-04  0.006878  0.979578  0.998064  0.998712  0.328627  0.982906  1.0
2023-12-05  0.006215  0.961667  0.998059  0.998064  0.331335  0.971510  1.0
2023-12-06  0.006749  0.962568  0.999987  1.000000  0.333112  0.982882  1.0
2023-12-07  0.007336  0.969251  0.983805  0.995238  0.335245  0.935404  1.0

[966 rows x

In [143]:
expanded_inputs=expanded_inputs2.copy()
print(expanded_inputs)

                  MA       RSI   STOCH_K   STOCH_D      MACD     WILLR  \
Date                                                                     
2020-01-09  0.000000  0.500000  0.500000  0.500000  0.500000  0.500000   
2020-01-10  0.000000  0.500000  0.500000  0.500000  0.500000  0.500000   
2020-01-13  0.000000  0.500000  0.500000  0.500000  0.500000  0.500000   
2020-01-14  0.000000  0.500000  0.500000  0.500000  0.500000  0.500000   
2020-01-15  0.000000  0.500000  0.500000  0.500000  0.500000  0.500000   
...              ...       ...       ...       ...       ...       ...   
2023-12-01  0.007591  0.979307  0.994191  0.945714  0.324367  0.977221   
2023-12-04  0.006878  0.979578  0.998064  0.998712  0.328627  0.982906   
2023-12-05  0.006215  0.961667  0.998059  0.998064  0.331335  0.971510   
2023-12-06  0.006749  0.962568  0.999987  1.000000  0.333112  0.982882   
2023-12-07  0.007336  0.969251  0.983805  0.995238  0.335245  0.935404   

                 cx3       cx5       

In [425]:
# aa=features['MA'].copy()
# print(aa)
# print(aa.shape)
# for i in range(len(aa)):
#     aa[i]=1
# print(aa)
# print(features['MA'])
# aa.columns=['constant']
# aa.rename(columns={'MA':'constant'})
# print(aa)


                  MA       RSI   STOCH_K   STOCH_D      MACD     WILLR   aa
Date                                                                       
2020-01-09  0.000000  0.500000  0.500000  0.500000  0.500000  0.500000  1.0
2020-01-10  0.000000  0.500000  0.500000  0.500000  0.500000  0.500000  1.0
2020-01-13  0.000000  0.500000  0.500000  0.500000  0.500000  0.500000  1.0
2020-01-14  0.000000  0.500000  0.500000  0.500000  0.500000  0.500000  1.0
2020-01-15  0.000000  0.500000  0.500000  0.500000  0.500000  0.500000  1.0
...              ...       ...       ...       ...       ...       ...  ...
2023-12-01  0.007591  0.979307  0.994191  0.945714  0.324367  0.977221  1.0
2023-12-04  0.006878  0.979578  0.998064  0.998712  0.328627  0.982906  1.0
2023-12-05  0.006215  0.961667  0.998059  0.998064  0.331335  0.971510  1.0
2023-12-06  0.006749  0.962568  0.999987  1.000000  0.333112  0.982882  1.0
2023-12-07  0.007336  0.969251  0.983805  0.995238  0.335245  0.935404  1.0

[966 rows x

In [345]:
# one=[1]*996
# dd=pd.DataFrame(one)
# print(dd.shape)

(996, 1)


In [297]:
# print(features[:1000].shape)
# print(expanded_inputs.shape)

(966, 6)
(966, 7)


In [118]:
# train=df2.iloc[:1000,:]
# test=df2.iloc[1000:,:]
# target_column = ['Tri'] 
# predictors = list(set(list(df2.columns))-set(target_column))
# X= train[predictors]
# print('X:')
# print(X.iloc[0])
# print(len(X.iloc[0]))
# print(len(X))
# print(X[0:50])
# y = train[target_column]
synaptic_weights = np.random.uniform(low=0, high=1, size=(n+d,1))
# synaptic_weights = np.append(synaptic_weights, 1)
print(synaptic_weights)


[[0.03243413]
 [0.95316865]
 [0.63558791]
 [0.28428718]
 [0.38709988]
 [0.22223643]
 [0.2825782 ]
 [0.82011277]
 [0.31183394]
 [0.20849067]
 [0.57435039]
 [0.98179054]]
